apiVersion: v1
kind: Service
metadata:
  name: vault-ext-svc # this is an external nodeport service
  namespace: vault-ns
  labels:
    app.kubernetes.io/name: vault
    app.kubernetes.io/instance: vault
    # annotations:
spec:
  type: NodePort
  publishNotReadyAddresses: true
  ports: 
    - name: http
      port: 8200
      targetPort: 8200
      nodePort: 32000
    - name: https
      port: 8201
      targetPort: 8201
  selector:
    app.kubernetes.io/name: vault
    app.kubernetes.io/instance: vault
    component: server
